//
// Generated By:JAX-WS RI IBM 2.2.1-07/09/2014 01:53 PM(foreman)- (JAXB RI IBM 2.2.3-07/07/2014 12:56 PM(foreman)-)
//

@javax.xml.bind.annotation.XmlSchema(namespace = "urn:issw:bare:wssec:cc:query")
package org.acme.cc.jaxws;
