//
// Generated By:JAX-WS RI IBM 2.2.1-07/09/2014 01:53 PM(foreman)- (JAXB RI IBM 2.2.3-07/07/2014 12:56 PM(foreman)-)
//


package org.acme.cc.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ccNo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="txnId" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "ccNo",
    "txnId"
})
@XmlRootElement(name = "QueryFault")
public class QueryFault {

    @XmlElement(required = true)
    protected String ccNo;
    protected int txnId;

    /**
     * Gets the value of the ccNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCcNo() {
        return ccNo;
    }

    /**
     * Sets the value of the ccNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCcNo(String value) {
        this.ccNo = value;
    }

    /**
     * Gets the value of the txnId property.
     * 
     */
    public int getTxnId() {
        return txnId;
    }

    /**
     * Sets the value of the txnId property.
     * 
     */
    public void setTxnId(int value) {
        this.txnId = value;
    }

}
