//
// Generated By:JAX-WS RI IBM 2.2.1-11/25/2013 11:48 AM(foreman)- (JAXB RI IBM 2.2.3-11/25/2013 12:35 PM(foreman)-)
//


package org.acme.cc.jaxws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

@WebService(name = "CCPortType", targetNamespace = "urn:issw:bare:wssec:cc:query")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CCPortType {


    /**
     * 
     * @param parameters
     * @return
     *     returns org.acme.cc.jaxws.QueryResponse
     * @throws QueryFaultMsg
     */
    @WebMethod(action = "ccQuery")
    @WebResult(name = "QueryResponse", targetNamespace = "urn:issw:bare:wssec:cc:query", partName = "parameters")
    public QueryResponse query(
        @WebParam(name = "QueryRequest", targetNamespace = "urn:issw:bare:wssec:cc:query", partName = "parameters")
        QueryRequest parameters)
        throws QueryFaultMsg
    ;

}
