//
// Generated By:JAX-WS RI IBM 2.2.1-11/25/2013 11:48 AM(foreman)- (JAXB RI IBM 2.2.3-11/25/2013 12:35 PM(foreman)-)
//

@javax.xml.bind.annotation.XmlSchema(namespace = "urn:issw:bare:wssec:cc:query")
package org.acme.cc.jaxws;
